import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1000, height: 1000 } });
await p.goto("http://localhost:4321/tools/preview.html", { waitUntil: "networkidle" });
const f = await (await p.$("#slt-resources-frame")).contentFrame();
await f.waitForSelector(".slt-input");
await p.screenshot({ path: "shot-1-idle.png" });
await f.fill(".slt-input", "grass valley");
await f.waitForSelector(".slt-item");
await p.waitForTimeout(500);
await p.screenshot({ path: "shot-2-search.png" });
await f.fill(".slt-input", "");
await f.click('.slt-state[data-state="MT"]');
await f.waitForFunction(() => document.querySelectorAll(".slt-item").length > 5);
await p.waitForTimeout(500);
await p.screenshot({ path: "shot-3-state.png" });
await p.setViewportSize({ width: 390, height: 900 });
await p.waitForTimeout(700);
await p.screenshot({ path: "shot-4-phone.png" });
await b.close();
console.log("shots written");
